 const textDataGrid = {
    columnMenuUnsort: "Nieposortowane",
    columnMenuSortAsc: "Sortuj rosnąco",
    columnMenuSortDesc: "Sortuj malejąco",
    toolbarExport: "Pobierz",
    toolbarQuickFilterPlaceholder: 'Szukaj...',
    toolbarExportCSV:"Pobierz jako CSV",
    toolbarExportPrint: 'Wydrukuj',
    noRowsLabel: 'Nic nie znaleziono',
    columnsPanelTextFieldLabel: 'Znajdz kolumne',
    columnsPanelTextFieldPlaceholder: 'Nazwa kolumny',
    columnsPanelDragIconLabel: 'Reorder column',
    columnsPanelShowAllButton: 'Pokaż wszystkie',
    columnsPanelHideAllButton: 'Ukryj wszystkie',
    toolbarFilters: 'Filtruj',
    columnMenuHideColumn: 'Ukryj',
    columnMenuShowColumns: 'Pokaż kolumny',
    filterOperatorContains: 'zawiera',
    filterOperatorEquals: 'jest równy',
    filterOperatorStartsWith: 'zaczyna się',
    filterOperatorEndsWith: 'kończy się',
    filterOperatorIs: 'jest',
    filterOperatorNot: 'nie ma',
    filterOperatorAfter: 'jest po',
    filterOperatorOnOrAfter: 'jest włączony lub po',
    filterOperatorBefore: 'jest przed',
    filterOperatorOnOrBefore: 'jest włączony lub przed',
    filterOperatorIsEmpty: 'jest puste',
    filterOperatorIsNotEmpty: 'nie jest puste',
    filterOperatorIsAnyOf: 'jest którykolwiek z',
    filterValueAny: 'Każdy',
    filterValueTrue: 'Prawda',
    filterValueFalse: 'Fałsz',
    filterPanelOperators: 'Operator', 
    filterPanelOperatorAnd: 'I',
    filterPanelOperatorOr: 'Lub',
     filterPanelColumns: 'Kolumny',
    filterPanelInputLabel: 'Wartość',
    filterPanelInputPlaceholder: 'Wartość',
    errorOverlayDefaultLabel: 'Wystąpił błąd!',
    noRowsLabel: 'Brak wierszy',
    noResultsOverlayLabel: 'Nie znaleziono',
    footerRowSelected: (count) =>
    count !== 1
      ? `${count.toLocaleString()} wiersze wybrane`
      : `${count.toLocaleString()} wiersz wybrany`,

     footerTotalRows: 'Liczba wierszy:',
     toolbarDensity: 'Rodzaj Tabeli',
     toolbarDensityLabel: 'Rodzaj Tabeli',
     toolbarDensityCompact: 'Mała',
     toolbarDensityStandard: 'Standardowa',
     toolbarDensityComfortable: 'Duża',
     
  };
  
  export default textDataGrid;